apiVersion: v1
kind: Service
metadata:
  name: tibia-pvp-api
  namespace: tibia-pvp-api
spec:
  type: NodePort
  selector:
    app: tibia-pvp-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30722  # Porta externa (30000-32767)

